# Secrets for GameMaster's Companion
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gamemaster-companion.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gamemaster-companion.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  database-url: {{ include "gamemaster-companion.databaseUrl" . | b64enc | quote }}
  database-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  
  # Redis credentials (if auth enabled)
  {{- if .Values.redis.auth.enabled }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
  redis-url: {{ include "gamemaster-companion.redisUrl" . | b64enc | quote }}
  
  # Application secrets
  jwt-secret: {{ .Values.global.jwtSecret | default (randAlphaNum 32) | b64enc | quote }}
  api-key: {{ .Values.global.apiKey | default (randAlphaNum 64) | b64enc | quote }}
  encryption-key: {{ .Values.global.encryptionKey | default (randAlphaNum 32) | b64enc | quote }}
  
  # External service credentials (if enabled)
  {{- if .Values.integrations.discord.enabled }}
  discord-bot-token: {{ .Values.integrations.discord.botToken | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.integrations.dndbeyond.enabled }}
  dndbeyond-api-key: {{ .Values.integrations.dndbeyond.apiKey | default "" | b64enc | quote }}
  {{- end }}
  
  # vLLM API credentials (if needed)
  {{- if .Values.ai.vllm.enabled }}
  vllm-api-key: {{ .Values.ai.vllm.apiKey | default "local-development" | b64enc | quote }}
  {{- end }}
---
# Service account for pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gamemaster-companion.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gamemaster-companion.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}