apiVersion: v2
name: gamemaster-companion
description: A privacy-first, self-hosted D&D campaign management platform with local AI processing
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/gamemaster-companion/gmc
sources:
  - https://github.com/gamemaster-companion/gmc
maintainers:
  - name: GameMaster's Companion Team
    email: dev@gamemaster-companion.local
keywords:
  - dnd
  - rpg
  - gamemaster
  - ai
  - self-hosted
dependencies:
  # Use Bitnami charts for reliable data services
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  # Local monitoring stack
  - name: kube-prometheus-stack
    version: 54.2.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
  # Elasticsearch for search functionality
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: search.elasticsearch.enabled
annotations:
  category: Gaming
  licenses: MIT